const colors = {
  indigo0: "#E0E8F9",
  indigo1: "#BED0F7",
  indigo2: "#98AEEB",
  indigo3: "#7B93DB",
  indigo4: "#647acb",
  indigo5: "#4C63B6",
  indigo6: "#4055A8",
  indigo7: "#35469C",
  indigo8: "#2D3A8C",
  indigo9: "#19216C",

  gray0: "#F5F7FA",
  gray1: "#E4E7EB",
  gray2: "#CBD2D9",
  gray3: "#9AA5B1",
  gray4: "#7B8794",
  gray5: "#616E7C",
  gray6: "#52606D",
  gray7: "#3E4C59",
  gray8: "#323F4B",
  gray9: "#1F2933",

  blackText: "#3d5866",
  blackText: "#3d5866"
};

const theme = {
  indigo0: "#E0E8F9",
  indigo1: "#BED0F7",
  indigo2: "#98AEEB",
  indigo3: "#7B93DB",
  indigo4: "#647acb",
  indigo5: "#4C63B6",
  indigo6: "#4055A8",
  indigo7: "#35469C",
  indigo8: "#2D3A8C",
  indigo9: "#19216C",

  gray0: "#F5F7FA",
  gray1: "#E4E7EB",
  gray2: "#CBD2D9",
  gray3: "#9AA5B1",
  gray4: "#7B8794",
  gray5: "#616E7C",
  gray6: "#52606D",
  gray7: "#3E4C59",
  gray8: "#323F4B",
  gray9: "#1F2933",

  vividBlue0: "#E3F8FF",
  vividBlue1: "#B3ECFF",
  vividBlue2: "#81DEFD",
  vividBlue3: "#5ED0FA",
  vividBlue4: "#40C3F7",
  vividBlue5: "#2BB0ED",
  vividBlue6: "#1992D4",
  vividBlue7: "#127FBF",
  vividBlue8: "#0B69A3",
  vividBlue9: "#035388",

  red0: "#FFE3E3",
  red1: "#FFBDBD",
  red2: "#FF9B9B",
  red3: "#F86A6A",
  red4: "#EF4E4E",
  red5: "#E12D39",
  red6: "#CF1124",
  red7: "#AB091E",
  red8: "#8A041A",
  red9: "#610316",

  teal0: "#EFFCF6",
  teal1: "#C6F7E2",
  teal2: "#8EEDC7",
  teal3: "#65D6AD",
  teal4: "#3EBD93",
  teal5: "#27AB83",
  teal6: "#199473",
  teal7: "#147D64",
  teal8: "#0C6B58",
  teal9: "#014D40",

  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64, 96],

  // text Colors...
  blackText: colors["blackText"],
  highlightedText: colors.indigo9,
  disabledText: colors["gray4"],

  background: colors["gray1"],
  border: colors["vividBlue4"],

  sidebarWidth: "18vw",
  controlPanelWidth: "22vw",
  black: "#393939",
  bs: "0 12px 24px 0 rgba(0, 0, 0, 0.09)",
  dropShadow1: "1px 1px 7px 5px rgba(0, 0, 0, 0.1)",
  dropShadowPizzazz: "0 0 5px 3px rgba(0, 170, 170, 0.9)",
  perimeterShadow: "1px 1px 5px 3px rgba(0, 0, 0, 0.15)",
  hoveringDropdownShadow: "5px 5px 6px 5px rgba(0, 0, 0, 0.10)",
  navHeight: `4rem`,
  mobileStatusBarHeight: "3rem",
  mobileSubNavHeight: "5rem",
  mobileMainTop: "8rem",

  largeScreen: "787px",
  borderRadius: "5px",

  //Permalink: https://colorlab.dev/WyIxLjAuMCIsIiMzYjhhZWIiLDExLDAsMCwiaHNsdXYiLCJsaW5lYXIiXQ==
  // Generated by colorlab.dev
  // https://colorlab.dev/WyIxLjAuMCIsIiMzYjhhZWIiLDExLDAsMCwiaHNsdXYiLCJsaW5lYXIiXQ==
  //
  // Base: #3b8aeb
  // Stops: 11
  // Easing: linear
  // Mode: hsluv
  // Hue-shift: 0, 0

  // ****** NEW COLORS BELOW *******//
  cranberry: "#b23850",
  cream: "#e7e3d4",

  newBlue: {
    "0": {
      hex: "#fcfcff",
      css: "rgb(252,252,255)",
      hsl: "hsl(240,100%,99.41%)",
      rgb: {
        r: 252,
        g: 252,
        b: 255
      }
    },
    "10": {
      hex: "#d3d6fc",
      css: "rgb(211,214,252)",
      hsl: "hsl(235.61,87.23%,90.78%)",
      rgb: {
        r: 211,
        g: 214,
        b: 252
      }
    },
    "20": {
      hex: "#c2c7fb",
      css: "rgb(194,199,251)",
      hsl: "hsl(234.74,87.69%,87.25%)",
      rgb: {
        r: 194,
        g: 199,
        b: 251
      }
    },
    "30": {
      hex: "#a5acf9",
      css: "rgb(165,172,249)",
      hsl: "hsl(235,87.5%,81.18%)",
      rgb: {
        r: 165,
        g: 172,
        b: 249
      }
    },
    "40": {
      hex: "#8792f7",
      css: "rgb(135,146,247)",
      hsl: "hsl(234.11,87.5%,74.9%)",
      rgb: {
        r: 135,
        g: 146,
        b: 247
      }
    },
    "50": {
      hex: "#6778f5",
      css: "rgb(103,120,245)",
      hsl: "hsl(232.82,87.65%,68.24%)",
      rgb: {
        r: 103,
        g: 120,
        b: 245
      }
    },
    "60": {
      hex: "#425df1",
      css: "rgb(66,93,241)",
      hsl: "hsl(230.74,86.21%,60.2%)",
      rgb: {
        r: 66,
        g: 93,
        b: 241
      }
    },
    "70": {
      hex: "#2145da",
      css: "rgb(33,69,218)",
      hsl: "hsl(228.32,73.71%,49.22%)",
      rgb: {
        r: 33,
        g: 69,
        b: 218
      }
    },
    "80": {
      hex: "#1734ab",
      css: "rgb(23,52,171)",
      hsl: "hsl(228.24,76.29%,38.04%)",
      rgb: {
        r: 23,
        g: 52,
        b: 171
      }
    },
    "90": {
      hex: "#0e247e",
      css: "rgb(14,36,126)",
      hsl: "hsl(228.21,80%,27.45%)",
      rgb: {
        r: 14,
        g: 36,
        b: 126
      }
    },
    "100": {
      hex: "#061554",
      css: "rgb(6,21,84)",
      hsl: "hsl(228.46,86.67%,17.65%)",
      rgb: {
        r: 6,
        g: 21,
        b: 84
      }
    }
  },
  colorBox213: {
    "0": "#f5f9ff",
    "5": "#e1eeff",
    "10": "#cde3fe",
    "20": "#a6cdfd",
    "30": "#82b8fa",
    "40": "#62a5f7",
    "50": "#4895f3",
    "60": "#3287ee",
    "70": "#227be8",
    "80": "#1570e0",
    "90": "#0b67d7",
    "100": "#055ecc",
    "110": "#0057c1",
    "120": "#0051b5"
  }
};

export { theme };

// parentBg: "#C8CDE5",
// color: "#1F567A",
// bg: "#D0EDF1",
// border: "#0F2417",

// parentBg: "#d6e9f5",
// color: "#4e5255",
// bg: "#f7f7f8",
// border: "#d0edf1",

// parentBg: "#c8cde5",
// color: "#164249",
// bg: "#f7f7f8",
// border: "#0F2417",

// Generated by colorlab.dev
// https://colorlab.dev/WyIxLjAuMCIsIiNkM2Q2ZmMiLDExLDAsMCwiaHNsdXYiLCJsaW5lYXIiXQ==
//
// Base: #d3d6fc
// Stops: 11
// Easing: linear
// Mode: hsluv
// Hue-shift: 0, 0

// {
//   "0": {
//     hex: "#fbfcff",
//     css: "rgb(251,252,255)",
//     hsl: "hsl(225,100%,99.22%)",
//     rgb: {
//       r: 251,
//       g: 252,
//       b: 255,
//     },
//   },
//   "10": {
//     hex: "#d9e3fb",
//     css: "rgb(217,227,251)",
//     hsl: "hsl(222.35,80.95%,91.76%)",
//     rgb: {
//       r: 217,
//       g: 227,
//       b: 251,
//     },
//   },
//   "20": {
//     hex: "#b6caf8",
//     css: "rgb(182,202,248)",
//     hsl: "hsl(221.82,82.5%,84.31%)",
//     rgb: {
//       r: 182,
//       g: 202,
//       b: 248,
//     },
//   },
//   "30": {
//     hex: "#8fb2f5",
//     css: "rgb(143,178,245)",
//     hsl: "hsl(219.41,83.61%,76.08%)",
//     rgb: {
//       r: 143,
//       g: 178,
//       b: 245,
//     },
//   },
//   "40": {
//     hex: "#629bf2",
//     css: "rgb(98,155,242)",
//     hsl: "hsl(216.25,84.71%,66.67%)",
//     rgb: {
//       r: 98,
//       g: 155,
//       b: 242,
//     },
//   },
//   "50": {
//     hex: "#3b8aeb",
//     css: "rgb(59,138,235)",
//     hsl: "hsl(213.07,81.48%,57.65%)",
//     rgb: {
//       r: 59,
//       g: 138,
//       b: 235,
//     },
//   },
//   "60": {
//     hex: "#2d6ebd",
//     css: "rgb(45,110,189)",
//     hsl: "hsl(212.92,61.54%,45.88%)",
//     rgb: {
//       r: 45,
//       g: 110,
//       b: 189,
//     },
//   },
//   "70": {
//     hex: "#235899",
//     css: "rgb(35,88,153)",
//     hsl: "hsl(213.05,62.77%,36.86%)",
//     rgb: {
//       r: 35,
//       g: 88,
//       b: 153,
//     },
//   },
//   "80": {
//     hex: "#194478",
//     css: "rgb(25,68,120)",
//     hsl: "hsl(212.84,65.52%,28.43%)",
//     rgb: {
//       r: 25,
//       g: 68,
//       b: 120,
//     },
//   },
//   "90": {
//     hex: "#103057",
//     css: "rgb(16,48,87)",
//     hsl: "hsl(212.96,68.93%,20.2%)",
//     rgb: {
//       r: 16,
//       g: 48,
//       b: 87,
//     },
//   },
//   "100": {
//     hex: "#071d39",
//     css: "rgb(7,29,57)",
//     hsl: "hsl(213.6,78.13%,12.55%)",
//     rgb: {
//       r: 7,
//       g: 29,
//       b: 57,
//     },
//   },
//   stops: 11,
//   default: {
//     hex: "#3b8aeb",
//     css: "rgb(59,138,235)",
//     hsl: "hsl(213.07,81.48%,57.65%)",
//     rgb: {
//       r: 59,
//       g: 138,
//       b: 235,
//     },
//   },
//   defaultStop: 50,
// },
